title: Renegade Arcade
description: A knowledge base for video game mechanics and programming techniques.
theme: just-the-docs
color_scheme: dark

url: https://ericabxy.github.io/renegade-arcade

plugins:
- jekyll-default-layout
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-titles-from-headings

aux_links:
  Template Repository: https://github.com/ericabxy/renegade-arcade

collections:
  feeds:
    output: true
    permalink: "/:path"
  games:
    output: true
    permalink: "/:path"

defaults:
-
  scope:
    path: ""
    type: "games"
  values:
    title: /:path
-
  scope:
    path: "README.md"
  values:
    nav_exclude: true

just_the_docs:
  collections:
    games:
      name: Games
